name: CI/CD for Homework-7

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Checke den Code aus
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: homework-7

      # Schritt 2: Setup JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Schritt 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/homework-7/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Schritt 4: Install dependencies
      - name: Install dependencies
        run: mvn -f homework-7/pom.xml dependency:resolve

      # Schritt 5: Run tests
      - name: Run tests
        run: mvn -f homework-7/pom.xml test

      # Schritt 6: Generate JaCoCo test coverage
      - name: Generate JaCoCo test coverage
        run: mvn -f homework-7/pom.xml jacoco:report

      # Schritt 7: Upload JaCoCo coverage report
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: homework-7/target/site/jacoco
